#ifndef ADVANCED_PROGRAMMING_GROUP_XAVIER_INITIALIZATION_THRESHOLDING_TEST_H
#define ADVANCED_PROGRAMMING_GROUP_XAVIER_INITIALIZATION_THRESHOLDING_TEST_H

#include "../include/Thresholding.h"

void testThresholdingGray();
void testThresholdingHSV();
void testThresholdingHSL();

#endif //ADVANCED_PROGRAMMING_GROUP_XAVIER_INITIALIZATION_THRESHOLDING_TEST_H